export const VERIFICATION_REQUESTED = "VERIFICATION_REQUESTED"
export const VERIFICATION_FAILED = "VERIFICATION_FAILED"

export const SIGNIN_REQUESTED = "SIGNIN_REQUESTED"
export const SIGNIN_SUCCEED = "SIGNIN_SUCCEED"
export const SIGNIN_FAILED = "SIGNIN_FAILED"

export const SIGNOUT_REQUESTED = "SIGNOUT_REQUESTED"
export const SIGNOUT_SUCCEED = "SIGNOUT_SUCCEED"
export const SIGNOUT_FAILED = "SIGNOUT_FAILED"

// export const SIGNUP_REQUESTED = "SIGNUP_REQUESTED"
// export const SIGNUP_SUCCEED = "SIGNUP_SUCCEED"
// export const SIGNUP_FAILED = "SIGNUP_FAILED"
